# -*- coding: utf-8 -*-
"""dataBallers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FRs6_S9mcUMz3oFS7xHZ5ZyImEsm_js
"""

import pandas as pd

dataplayers = pd.read_csv('playersData.csv')

livPl = dataplayers[dataplayers["Squad"] == "Liverpool" ]

print(livPl)

adults = dataplayers[(dataplayers["Pos"] == "FW") & (dataplayers["Born"]=="1999") ]



print(adults)

dataplayers.to_excel("playersDATA.xlsx")

